### ISSUE TITLE
Module not compiling on openSUSE Tumbleweed with Kernel version 4.7.2

### ISSUE THREAD

**Issue by happenpappen** [sophos/talpa#1]
Hi,

when compiling on an openSUSE Tumbleweed system with kernel version 4.7.2 i get this error:

  CC [M]  /home/ADESSO/stoppe/DevelopmentProjects/sophos_talpa/src/components/services/linux_filesystem_impl/linux_file.o
In file included from /usr/src/linux-4.7.2-2/include/linux/notifier.h:13:0,
                 from /usr/src/linux-4.7.2-2/include/linux/memory_hotplug.h:6,
                 from /usr/src/linux-4.7.2-2/include/linux/mmzone.h:737,
                 from /usr/src/linux-4.7.2-2/include/linux/gfp.h:5,
                 from /usr/src/linux-4.7.2-2/include/linux/slab.h:14,
                 from /home/ADESSO/stoppe/DevelopmentProjects/sophos_talpa/src/components/services/linux_filesystem_impl/linux_file.c:23:
/home/ADESSO/stoppe/DevelopmentProjects/sophos_talpa/src/components/services/linux_filesystem_impl/linux_file.c: In function ‘unlink’:
/home/ADESSO/stoppe/DevelopmentProjects/sophos_talpa/src/components/services/linux_filesystem_impl/linux_file.c:624:31: error: ‘struct inode’ has no member named ‘i_mutex’; did you mean ‘i_mode’?
     mutex_lock_nested(&parenti->i_mutex, I_MUTEX_PARENT);
                               ^
/usr/src/linux-4.7.2-2/include/linux/mutex.h:161:55: note: in definition of macro ‘mutex_lock_nested’
 # define mutex_lock_nested(lock, subclass) mutex_lock(lock)
                                                       ^~~~
/home/ADESSO/stoppe/DevelopmentProjects/sophos_talpa/src/components/services/linux_filesystem_impl/linux_file.c:643:26: error: ‘struct inode’ has no member named ‘i_mutex’; did you mean ‘i_mode’?
     mutex_unlock(&parenti->i_mutex);
                          ^~
make[6]: *** [/usr/src/linux-4.7.2-2/scripts/Makefile.build:292: /home/ADESSO/stoppe/DevelopmentProjects/sophos_talpa/src/components/services/linux_filesystem_impl/linux_file.o] Fehler 1
make[5]: *** [/usr/src/linux-4.7.2-2/Makefile:1483: _module_/home/ADESSO/stoppe/DevelopmentProjects/sophos_talpa] Fehler 2
make[4]: *** [Makefile:150: sub-make] Fehler 2
make[3]: *** [Makefile:24: __sub-make] Fehler 2
make[3]: Verzeichnis „/usr/src/linux-4.7.2-2-obj/x86_64/default“ wird verlassen
make[2]: *** [makefile:2248: talpa_core.ko] Fehler 2
make[2]: Verzeichnis „/home/ADESSO/stoppe/DevelopmentProjects/sophos_talpa“ wird verlassen
make[1]: *** [makefile:1817: all-recursive] Fehler 1
make[1]: Verzeichnis „/home/ADESSO/stoppe/DevelopmentProjects/sophos_talpa“ wird verlassen
make: *** [makefile:872: all] Fehler 2

I played around with the configure options:

  --enable-backported-mutexes
  --enable-inode_mutexes

but this doesn't resolve the error. I don't know if you need more informations to get into this, so please contact me if needed...

kind regards,

Christoph

**Comment by paperclip** [comment]
e9e500167c5460ec3941bac1f83f6e01bbf5a35c includes fixes for compiling on 4.7 kernels.
Hope this helps.
