### ISSUE TITLE
Not compiling on kernel 4.17.17

### ISSUE THREAD

**Issue by astronos2007** [sophos/talpa#13]
The talpa module is not compiling on kernel version 4.17.17. I am not able to use another one because of my laptop, which needs very new hardware support, offered only in the new kernels. Could you please investigate the problem? I attached the logs from "./bootstrap", "./configure", "./make", respectively.

[bootstrap.log](https://github.com/sophos/talpa/files/2532909/bootstrap.log)
[configure.log](https://github.com/sophos/talpa/files/2532910/configure.log)
[make.log](https://github.com/sophos/talpa/files/2532911/make.log)

**Comment by paperclip** [comment]
Please could you tell us your user-space environment? i.e. Operating system, gcc version

**Comment by astronos2007** [comment]
Sure. I am using:
- Debian 9.5 Stretch 64 bit
- kernel 4.17.0-0.bpo.1-amd64 #1 SMP Debian 4.17.17-1~bpo9+1 (2018-08-27) x86_64 GNU/Linux
- XFCE 4.6 Desktop environment
- GCC version: gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

**Comment by astronos2007** [comment]
Hi!
It is working flawlessly now. Thank you for the fix!
