### ISSUE TITLE
Make error while compiling on 4.19er kernel

### ISSUE THREAD

**Issue by pyriand3r** [sophos/talpa#14]
I have just tried to compile talpa on a kernel version 4.19.1 and got an error in the make command:

```
/home/user/ressourcen/talpa/src/components/intercepts/vfshook_impl/vfshook_interceptor.c:1475:32:
 Fehler: Zuweisung an »int (*)(struct inode *, struct dentry *, struct file *, unsigned int,  umode_t,  int *)« 
{alias »int (*)(struct inode *, struct dentry *, struct file *, unsigned int,  short unsigned int,  int *)«} von 
inkompatiblem Zeigertyp »int (*)(struct inode *, struct dentry *, struct file *, unsigned int,  umode_t)« 
{alias »int (*)(struct inode *, struct dentry *, struct file *, unsigned int,  short unsigned int)«} 
[-Werror=incompatible-pointer-types]
             patch->atomic_open = patch->i_ops->atomic_open;
```
My environment:

distribution: manjaro
kernel: 4.19.1-1-manjaro
gcc: 8.2.1 20180831
make: 4.2.1

Any suggestions on this?

**Comment by paperclip** [comment]
I'm afraid we haven't made Talpa work on kernel 4.19 yet.

**Comment by paperclip** [comment]
The Perforce branch now has the fixes for 4.19 kernel, it you'd like to try it.

**Comment by paperclip** [comment]
I've merged the change to master as well.

**Comment by pyriand3r** [comment]
Nice, i give it a try as soon as possible and will report back afterwards.

**Comment by joekiller** [comment]
I can confirm this builds on `4.19.8-arch1-1-ARCH`

**Comment by paperclip** [comment]
It appears to work on 4.19 in our internal tests, and we've had external confirmation, so I'm going to close this ticket - please raise a new one if you're still having problems.
