### ISSUE TITLE
talpa with linux 4.10

### ISSUE THREAD

**Issue by Pastim** [sophos/talpa#2]
I have just installed ubuntu 17.04.  This includes linux 4.10.0.  The talpa build now fails with:

......
checking for linux/dcache.h... yes
checking for __d_path prototype... available
checking for exported __d_path... undetectable
checking for linux/dcache.h... yes
checking for 2.6.38 style locking... post 2.6.38 style locking
checking for __d_path address... 0xffffffff812617f0
checking for __d_path type... struct path
checking for vfsmount and br lock... vfsmount lock is mount_lock seqlock
checking for __lookup_mnt_last address... configure: error: not found

Traceback (most recent call last):
  File "talpa_select.py", line 2176, in _action
  File "talpa_select.py", line 1074, in load
  File "talpa_select.py", line 841, in select
  File "talpa_select.py", line 1696, in select
  File "talpa_select.py", line 1780, in build
  File "talpa_select.py", line 1910, in __try_build
  File "talpa_select.py", line 1773, in checkConfigureErrors
SelectException: exc-configure-failed-freeversion

I believe that the  __lookup_mnt_last address function has been removed from linux 4.9 - see https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.9.15

**Comment by paperclip** [comment]
Hi,

I've raised a Jira ticket to add support for kernels 4.9 and 4.10 to Talpa.

I'm afraid a quick look at that commit suggests it won't be trivial to do the update.

**Comment by Pastim** [comment]
Thanks.  I guessed that that sort of issue might be non-trivial to resolve.  No matter, at least it's in hand.

I'm slightly puzzled as to why no one has seen it before.  Linux 4.9 was out at the end of last year.  Never mind.  :)

If there's a better way to report such things, please let me know.

**Comment by paperclip** [comment]
I get notified to a personal email from github, so forgot to reply until I got notified about the forum message from QC. SAV switches automatically to fanotify for most installs, so most people probably don't see the problem.

**Comment by Montecito** [comment]
The problematic change is in version 4.9.15, all versions before work fine.
I have a working version on  4.9.13.

Currently my workaround is to suppress kernel updates - hope a fix comes soon ;-)

**Comment by Montecito** [comment]
For the time being: 
If you are interested I created a fix (or better a hack) which lets you compile for 4.10:
https://github.com/Montecito/talpa/tree/perforce_4.10.x

SAV is working properly as far as I can say...

**Comment by paperclip** [comment]
Unfortunately disabling countPropogationPoints will break protection of namespaces - if you umount something inside a cloned namespace it will decrement the count and result in the filesystem not being protected.

**Comment by Pastim** [comment]
It looks like I had better wait until a complete solution is found, but thanks for the possibility!

**Comment by paperclip** [comment]
Perforce branch should have a fix for 4.9 and 4.10 kernels.

**Comment by Montecito** [comment]
As far as I can see that's basically the fix I proposed in my fork - but thanks for the fix anyway ;-)

I still get a configure error, because it cannot find the header file linux/version.h.
I will open another issue for that.

**Comment by Pastim** [comment]
Thanks - compiled and built and being used.  A heck of a lot of warnings such as:

tests/modules/common.mk:117: warning: source file 'src/components/services/linux_processandthread_impl/linux_threadinfo.c' is in a subdirectory,
tests/modules/common.mk:117: but option 'subdir-objects' is disabled
tests/modules/makefile.am:121:   'tests/modules/common.mk' included from here
tests/modules/common.mk:117: warning: source file 'src/components/services/linux_filesystem_impl/linux_systemroot.c' is in a subdirectory,
tests/modules/common.mk:117: but option 'subdir-objects' is disabled
tests/modules/makefile.am:121:   'tests/modules/common.mk' included from here

And many, many others, but all seems OK.

**Comment by paperclip** [comment]
autoconf/automake have changed the way they work with subdirs, but unfortunately we can't switch to the new way everywhere we want to support, so have to live with the warnings.
It only effects from github/perforce builds - the src pack included in the product already has the autoconf steps done.

**Comment by Pastim** [comment]
No worries - thanks.
