### ISSUE TITLE
How to restrain from caching specific file

### ISSUE THREAD

**Issue by akshaynikam49** [sophos/talpa#24]
If we enabled Talpa Cache, and we don't want some specific file to be cached, what are the ways to achieve that?

**Comment by paperclip** [comment]
When you send the response from user-space to Talpa you can indicate that you don't want the response to be cached. Sophos Anti-Virus for Linux uses this to indicate that files that have been excluded from scanning shouldn't be cached (as the exclusions can change without touching the file).

**Comment by akshaynikam49** [comment]
Is there any API or flag for this?
As I know, we send only TALPA_ALLOW or TALPA_DENY to Talpa using write() system call

**Comment by paperclip** [comment]
Sorry, looks like I was mis-remembering - exclusions inside Talpa are treated specially, and not cached. Exclusions in user-space are caches the same way as clean scans - and then the cache is dropped I think if the exclusions change.

I don't think there is any built-in way to avoid caching clean results from user-space. Entire filesystem types can be excluded from caching, which SAV uses for network filesystems.

**Comment by akshaynikam49** [comment]
@paperclip Thanks for the response

**Comment by paperclip** [comment]
Fanotify on the other hand has caching completely separate from responses, so userspace can select whether to cache dynamically.
