### ISSUE TITLE
configure: error: checking for linux/version.h

### ISSUE THREAD

**Issue by Montecito** [sophos/talpa#3]
When I run the configure script I get the following error:

checking for linux/version.h... configure: error: cannot proceed without the required header file

As far as I know the linux/version.h file is deprecated and no longer available in my distro (Arch linux).
I think the correct header file should be:
generated/uapi/linux/version.h

Can you confirm that?

**Comment by paperclip** [comment]
We search for the header in lots of places but haven't encountered generated/uapi.

We have ${kerneldir}/include/generated/uapi in our search path though. Our current search paths work for 2.6.18-4.10 kernels on our supported distributions.

**Comment by Montecito** [comment]
You are right, this issue is unrelated to the project, i had some installation issues locally.

It's now working as expected.
