### ISSUE TITLE
kernel 4.13 support

### ISSUE THREAD

**Issue by moozaad** [sophos/talpa#5]
build output (from deploy script)
```
'talpa-srcpack.tar.gz' -> '/opt/sophos-av/talpa/override/talpa-srcpack.tar.gz'
[Talpa-select]
Copyright 1989-2017 Sophos Limited. All rights reserved.
Fri Sep 22 09:32:25 2017 GMT
Linux distribution: [suse]
Product: [openSUSE Tumbleweed]
Kernel: [4.13.1-1-default]
Multiprocessor support enabled.
Searching for source pack...
Searching for suitable binary pack...
No suitable binary pack available.
Preparing for build...
Extracting sources...
Configuring build of version 0.9.95...
Building...
Error: Failed to build from source.
Unable to do talpa_select select
```
log:
```
Building...
Traceback (most recent call last):
  File "talpa_select.py", line 2216, in _action
  File "talpa_select.py", line 845, in select
  File "talpa_select.py", line 1736, in select
  File "talpa_select.py", line 1820, in build
  File "talpa_select.py", line 1973, in __try_build
SelectException: exc-build-failed
```

**Comment by paperclip** [comment]
Hi,
We haven't added 4.13 kernel support yet.
It would be useful if you could attach /opt/sophos-av/talpa/build/config.log and/or build.log in case those give any clues about how it is broken.

**Comment by moozaad** [comment]
/opt/sophos-av/talpa/build/talpa-0.9.95/config.log http://susepaste.org/84229032

build.log http://susepaste.org/81471307

Looking a the second, it's a warning as error issue. The newer GCC are a lot stricter and slightly different defaults.

gcc (SUSE Linux) 7.2.1 20170901 [gcc-7-branch revision 251580]

**Comment by paperclip** [comment]
Looks like someone else hit a similar issue at https://lkml.org/lkml/2017/6/20/24

**Comment by moozaad** [comment]
Changing https://github.com/sophos/talpa/blob/aa85271b90597743dad29a0ef98dd9bcf3bfd377/src/components/services/linux_filesystem_impl/linux_file.c#L334 to 
` struct path path = { .mnt=mnt, .dentry=dentry };` allows it to compile.

**Comment by Pastim** [comment]
I tried that change but the compilation still failed.  I edited "/opt/sophos-av/talpa/build/talpa-1.23.3/src/components/services/linux_filesystem_impl/linux_file.c" but the change got overwitten.  Is it extracted from the talpa-srcpack.tar.gz each time?

**Comment by moozaad** [comment]
You need to edit the version pulled with https://gist.github.com/paperclip/7892031 
It's just a git pull with some logic to make it run nice regularly.

**Comment by Pastim** [comment]
I did that (in /root/talpa/......) and that version has your patch, but it doesn't seem to get into /opt/sophos-av/..... 

I don't understand exactly what the update process is, so am unsure what happens next.

**Comment by Pastim** [comment]
As I understand it, autodeploy downloads the latest version (if changed), tars it, and copies the tar to the /opt/sophos-av/talpa folder.  From there it gets extracted by sophos-av.  So to get a patch in I need to amend the version within the tar file at some point.  Is that right?  If so, what's the best way?  As you can tell, I'm no expert at this stuff, but I usually manage to make things work in the end...

**Comment by moozaad** [comment]
looking at my console history I did

```
cd /root
mkdir talpa
./autodeploy.sh /root/talpa
vi talpa/src/components/services/linux_filesystem_impl/linux_file.c 
cd talpa
make talpa-srcpack.ta.gz
```
I can't confirm that works as I went back to using the inotify method instead.

**Comment by Pastim** [comment]
I cleared out root/talpa and started again.  I now get a failure on autodeploy.sh:

configure: error: conditional "TESTNAMESPACES" was never defined.
Usually this means the macro was only invoked conditionally.
Unable to configure

I'm on ubuntu 17.10.

**Comment by paperclip** [comment]
Hi,
I'm afraid I'm away this week, so I can't look at this at the moment, but I'll investigate it next week. 
I suspect something is broken in the tarfile-generating configuration, but I'll need to have a look.

**Comment by grandtoubab** [comment]
Hello
Same issue in Debian
https://community.sophos.com/products/free-antivirus-tools-for-desktops/f/sophos-free-tools/97218/can-t-compile-talpa-for-kernel-4-13-in-debian

**Comment by paperclip** [comment]
The TESTNAMESPACES problem should be fixed now.

**Comment by paperclip** [comment]
Fix commited https://github.com/sophos/talpa/commit/493b7dc16f6e9f0c8ce46ceee638fbfb986533be
to the perforce branch.
Tested on Ubuntu 17.10 4.13.0-16-generic kernel.

**Comment by Pastim** [comment]
Sorry, I'm going to have to ask for a little more help.
I went to autodeploy.sh on github (https://gist.github.com/paperclip/7892031) and downloaded it but it hasn't changed there, I still get the compilation error.
I don't know if you have fixed autodeploy (for TESTNAMESPACES), or the talpa code for the linux_file.c issue mentioned earlier, or both, but without a working autodeploy I can't get the compilation to work.

**Comment by Pastim** [comment]
I should have deleted the root/talpa directory.  I think all is well now. Sorry for my previous confusion about where the fix was made.

**Comment by paperclip** [comment]
The autodeploy.sh script should update from github every time it runs. Maybe you ended up pointing to a different branch?

**Comment by Pastim** [comment]
Talpa gave the same TESTNAMESPACES error until I deleted root/talpa.  I had also downloaded autodeploy.sh again, so maybe that was why it didn't work 1st time.
Anyway, it's up and running now.

Thanks very much for our help.

**Comment by rajneesh-kumar-sharma** [comment]
Sophos is updating properly on rhel 6 but not on rhel 7.5.

**Comment by paperclip** [comment]
> Sophos is updating properly on rhel 6 but not on rhel 7.5.

Hi, this is an old Talpa github issue - I think you should contact Sophos support if you have a problem with SAV.
